<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Smartwave\Filterproducts\Block\
 */
?>
<?php
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
  $_productCollection = $block->getProductCollection()->getItems();
  $_helper = $this->helper('Magento\Catalog\Helper\Output');
  $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');

  $_portohelper = $this->helper('Smartwave\Porto\Helper\Data');

  $_category_config = $_portohelper->getConfig('porto_settings/category');
  $_category_grid_config = $_portohelper->getConfig('porto_settings/category_grid');
  $_lazyload = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/optimization/lazyload');

  $aspect_ratio = $this->getData("aspect_ratio");
  if($aspect_ratio == null) {
      $aspect_ratio = $_category_config['aspect_ratio'];
  }
  $image_width = $this->getData("image_width");
  if(!$image_width) {
      $image_width = ($_category_config['ratio_width'])?$_category_config['ratio_width']:300;
  }
  $image_height = $this->getData("image_height");
  if($aspect_ratio)
      $image_height = $image_width;
  if(!$image_height) {
      $image_height = ($_category_config['ratio_height'])?$_category_config['ratio_height']:300;
  }
  $show_slide_nav = 'false';
  if($this->hasData("show_slide_nav")){
    $show_slide_nav = $this->getData("show_slide_nav") > 0 ? 'true': 'false';
  }
  $show_slide_page = 'false';
  if($this->hasData("show_slide_page")) {
    $show_slide_page = $this->getData("show_slide_page") > 0 ? 'true': 'false';
  }
  $enable_autoplay = 'false';
  if($this->hasData("enable_autoplay")) {
    $enable_autoplay = $this->getData("enable_autoplay") > 0 ? 'true': 'false';
  }
  $id = $block->getData('page_var_name') . uniqid('', false);
}
?>
<?php if (!$exist): ?>
    <div class="message info empty"><div><?php echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $hover_image = 'category_page_grid-hover';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    ?>
    <div id="side_product_<?php echo $id;?>">
      <div class="products wrapper <?php echo $viewMode; ?> small-list products-<?php echo $viewMode; ?>">
          <?php $iterator = 0; ?>
          <div class="filterproducts products list items product-items owl-carousel mb-0 show-nav-title">
              <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
              <?php foreach ($_productCollection as $_product): ?>
              <?php if(($iterator % 3) == 0): ?>
              <div class="item">
              <?php endif; ?>
              <?php $iterator ++; ?>
                  <div class="product product-item">
                  <div class="product-item-info" data-container="product-grid">
                      <?php // Product Image ?>
                      <a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                          <?php
                              if($aspect_ratio)
                                  $productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                              else
                                  $productImage = $_imagehelper->init($_product, $image)->resize($image_width, $image_height);
                              $productImageUrl = $productImage->getUrl();
                          ?>
                              <img class="product-image-photo default_image <?php if(!$_lazyload): ?>porto-lazyload<?php endif;?>" <?php if(!$_lazyload): ?>data-<?php endif; ?>src="<?php echo $productImageUrl; ?>" width="<?php echo $image_width; ?>" height="<?php echo $image_height; ?>" alt="<?php //echo $productImage->getLabel();?>"/>
                          <?php if($_category_config['alternative_image']): ?>
                          <?php
                              if($aspect_ratio)
                                  $productHoverImage = $_imagehelper->init($_product, $hover_image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                              else
                                  $productHoverImage = $_imagehelper->init($_product, $hover_image)->resize($image_width, $image_height);
                              $productHoverImageUrl = $productHoverImage->getUrl();
                          ?>
                              <?php if($productImageUrl != str_replace("/thumbnail/","/small_image/",$productHoverImageUrl)): ?>
                              <img class="product-image-photo hover_image" src="<?php echo $productHoverImageUrl; ?>" alt="<?php //echo $productHoverImage->getLabel();?>"/>
                              <?php endif; ?>
                          <?php endif; ?>
                      </a>
                      <div class="product details product-item-details">
                          <?php
                              $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                          ?>
                          <a href="<?php echo $_product->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                          <?php if($_category_config['rating_star']): ?>
                          <?php
                              $review_html = $block->getReviewsSummaryHtml($_product, $templateType);
                          ?>
                          <?php if($review_html): ?>
                              <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                          <?php else: ?>
                          <div class="product-reviews-summary short">
                              <div class="rating-summary">
                                  <span class="label"><span>Rating:</span></span>
                                  <div class="rating-result" title="0%">
                                      <span style="width:0"><span>0%</span></span>
                                  </div>
                              </div>
                          </div>
                          <?php endif; ?>
                          <?php endif; ?>
                          <?php if ($showDescription):?>
                              <div class="product description product-item-description">
                                  <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                  <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>"
                                     class="action more"><?php echo __('Learn More') ?></a>
                              </div>
                          <?php endif; ?>
                          <?php if($_category_config['product_price']): ?>
                          <?php echo $block->getProductPrice($_product) ?>
                          <?php endif; ?>
                          <?php echo $block->getProductDetailsHtml($_product); ?>
                      </div>
                  </div>
                  </div>
                  <?php if(($iterator % 3) == 0 || $iterator == count($_productCollection)): ?>
                  </div>
                  <?php endif; ?>
              <?php endforeach; ?>
          </div>
      </div>
      <script type="text/javascript">
        require([
          'jquery',
          'owlcarousel',
          'lazyload'
        ], function ($) {
          $("#side_product_<?php echo $id;?> .owl-carousel").owlCarousel({
            autoplay: <?php echo $enable_autoplay;?>,
            autoplayTimeout: 5000,
            loop: false,
            items: 1,
            nav: <?php echo $show_slide_nav;?>,
            dots: <?php echo $show_slide_page;?>
          });
          $("img.porto-lazyload:not(.porto-lazyload-loaded)").lazyload({effect:"fadeIn", effect_speed: 400 });
          if ($('.porto-lazyload:not(.porto-lazyload-loaded)').closest('.owl-carousel').length) {
              $('.porto-lazyload:not(.porto-lazyload-loaded)').closest('.owl-carousel').on('initialized.owl.carousel', function() {
                  $(this).find('.porto-lazyload:not(.porto-lazyload-loaded)').trigger('appear');
              });
              $('.porto-lazyload:not(.porto-lazyload-loaded)').closest('.owl-carousel').on('changed.owl.carousel', function() {
                  $(this).find('.porto-lazyload:not(.porto-lazyload-loaded)').trigger('appear');
              });
          }
          window.setTimeout(function(){
              $('.sidebar-filterproducts').find('.porto-lazyload:not(.porto-lazyload-loaded)').trigger('appear');
          },500);
        });
      </script>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
