<?php
// Используем метод getSaleableItem() для получения продукта
$product = $block->getSaleableItem();

// Проверяем, если продукт успешно найден
if ($product && $product->getTypeId() === \Magento\GroupedProduct\Model\Product\Type\Grouped::TYPE_CODE) {
    // Рассчитываем общую цену для группированных продуктов
    $totalPrice = 0;
    $associatedProducts = $product->getTypeInstance()->getAssociatedProducts($product);
    foreach ($associatedProducts as $associatedProduct) {
        $totalPrice += $associatedProduct->getFinalPrice();
    }
}

?>

<div class="price-box">
    <?php if (isset($totalPrice) && $totalPrice > 0): ?>
        <p class="minimal-price">
            <span class="price-label"><?= $block->escapeHtml(__('Total Price')) ?></span>
            <span class="price"><?= $block->escapeHtml(
                $this->helper(\Magento\Framework\Pricing\Helper\Data::class)->currency($totalPrice, true, false)
            ); ?></span>
        </p>
    <?php endif; ?>
</div>
