<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
    $custom_block = Mage::getStoreConfig('porto_settings/header/static_block', $code);
?>
<div class="header-container type28 header-newskin">
    <div class="top-links-container">
        <div class="top-links container">
            <div class="header-top-left">
                <?php echo '<div class="custom-block">'.$this->getLayout()->createBlock('cms/block')->setBlockId($custom_block)->toHtml().'</div>'; ?>
            </div>
            <div class="header-top-right">
                <?php
                $store_currency = $this->getChildHtml('store_currency');
                $store_language = $this->getChildHtml('store_language');
                ?>
                <?php echo $store_currency; ?>
                <?php echo $store_language; ?>
            </div>
        </div>
    </div>
    <div class="header container">
        <?php if ($this->getIsHomePage()):?>
        <h1 class="logo"><strong><?php echo $this->getLogoAlt(); ?></strong><a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo"><img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" /></a></h1>
        <?php else:?>
        <a href="<?php echo $this->getUrl(''); ?>" title="<?php echo $this->getLogoAlt(); ?>" class="logo"><strong><?php echo $this->getLogoAlt(); ?></strong><img src="<?php echo $this->getLogoSrc(); ?>" alt="<?php echo $this->getLogoAlt(); ?>" /></a>
        <?php endif; ?>
        <div class="header-main-right">
            <div class="menu-icon"><a href="javascript:void(0)" title="<?php echo $this->__('Menu'); ?>"><i class="fa fa-bars"></i><span><?php echo $this->__('Menu'); ?></span></a></div>
            <div class="search-area">
                <a href="javascript:void(0);" class="search-icon"><i class="icon-magnifier"></i><span><?php echo $this->__('Search'); ?></a>
                <?php echo $this->getChildHtml('topSearch'); ?>
            </div>
            <div class="top-links-area">
                <div class="top-links-icon"><a href="javascript:void(0)"><i class="porto-new-icon-user-2"></i></a></div>
                <?php echo $this->getChildHtml('topLinks'); ?>
            </div>
            <div class="wishlist-link">
                <a href="<?php echo $this->getUrl('wishlist'); ?>" title="<?php echo $this->__('Wishlist'); ?>"><i class="porto-new-icon-wishlist-2"></i></a>
            </div>
            <?php echo $this->getChildHtml('minicart'); ?>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('mobile.nav') ?>